### ISSUE TITLE
Manual total price ( Rewrite)

### ISSUE THREAD

**Issue by cihanx** [ConsoleTVs/Invoices#52]
Hi guys, I want to custom total price rewrite.

Example: 
product price: 1 quantity 90 USD = 1*90 =  total price 90 USD
2 quantity 160 USD = 2*160 = 320 USD (problem)

how to custom rewrite total price in my invoices?

**Comment by ConsoleTVs** [comment]
as far as I know, this can still be done in PHP and then calculate the individual price. eg:

if quantity = 1 and price = 90, unit price: 90
if quantity = 2 and price = 160, unit price: 80

Since you know the quantity and the price and can calculate the unit price as show, you just need to
tell invoices that:

For the second one (quantity = 2 and price = 160)
```php
->addItem('Test Item', 80, 2, 0000)
```

This feature is not integrated into invoices because this is a complex topic, not everybody handles different prices the same ways. It's best to manually do it. Not much code you need to write either...
